apiVersion: v1
kind: Secret
metadata:
  name: {{ include "xnat-web.fullname" . }}
  labels:
    {{- include "xnat-web.labels" . | nindent 4 }}
type: Opaque
stringData:
  xnat-conf.properties: |
    #
    # xnat-conf.properties
    # XNAT http://www.xnat.org
    # Copyright (c) 2016, Washington University School of Medicine
    # All Rights Reserved
    #
    # Released under the Simplified BSD.
    #
    datasource.driver=org.postgresql.Driver
    datasource.url=jdbc:postgresql://{{ template "xnat-web.postgresql.fullname" . }}/{{ template "xnat-web.postgresql.postgresqlDatabase" . }}
    datasource.username={{ template "xnat-web.postgresql.postgresqlUsername" . }}
    datasource.password={{ template "xnat-web.postgresql.postgresqlPassword" . }}
    hibernate.dialect=org.hibernate.dialect.PostgreSQL9Dialect
    hibernate.hbm2ddl.auto=update
    hibernate.show_sql=false
    hibernate.cache.use_second_level_cache=true
    hibernate.cache.use_query_cache=true
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "xnat-web.fullname" . }}-auth
  labels:
    {{- include "xnat-web.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $method, $m := .Values.authentication.methods }}
  {{- if eq $method "openid" }}
  openid-provider.properties: |
    name={{ $m.name }}
    provider.id=openid
    auth.method=openid
    # OpenID method specific configuration
    type=openid
    enabled={{ keys $m.providers | sortAlpha | join "," }}
    visible=true
    auto.enabled=true
    auto.verified=true
    disableUsernamePasswordLogin={{ $m.disableUsernamePasswordLogin }}
    siteUrl={{ $m.siteUrl }}
    preEstablishedRedirUri=/openid-login
    {{- range $provider, $p := $m.providers }}
    {{ $method }}.{{ $provider }}.clientID={{ $p.clientID }}
    {{ $method }}.{{ $provider }}.clientSecret={{ $p.clientSecret }}
    {{ $method }}.{{ $provider }}.accessTokenUri={{ $p.accessTokenUri }}
    {{ $method }}.{{ $provider }}.userAuthUri={{ $p.userAuthUri }}
    {{ $method }}.{{ $provider }}.scopes={{ range $i, $e := $p.scopes }}{{ if $i }},{{ end }}{{ $e }}{{ end }}
    {{ $method }}.{{ $provider }}.link={{ $p.link }}
    {{ $method }}.{{ $provider }}.shouldFilterEmailDomains={{ if $p.allowedEmailDomains }}true{{ else }}false{{ end }}
    {{ $method }}.{{ $provider }}.allowedEmailDomains={{ range $i, $e := $p.allowedEmailDomains }}{{ if $i }},{{ end }}{{ $e }}{{ end }}
    {{ $method }}.{{ $provider }}.forceUserCreate={{ $p.forceUserCreate }}
    {{ $method }}.{{ $provider }}.userAutoEnabled={{ $p.userAutoEnabled }}
    {{ $method }}.{{ $provider }}.userAutoVerified={{ $p.userAutoVerified }}
    {{- range $property, $attribute := $p.propertyNames }}
    {{ $method }}.{{ $provider }}.{{ $property }}Property={{ $attribute }}
    {{- end }}
    {{- end }}
  {{- end }}
  {{- if eq $method "ldap" }}
  {{- range $provider, $p := .providers }}
  {{- if $p.address }}
  {{ $provider }}-provider.properties: |
    name={{ $p.name }}
    provider.id={{ $provider }}
    auth.method={{ $method }}
    address={{ $p.address }}
    userdn={{ $p.userdn }}
    password={{ $p.password }}
    search.base={{ $p.search.base }}
    search.filter={{ $p.search.filter }}
  {{- end }}
  {{- end }}
  {{- end }}
  {{- end }}
