name: github pages

on:
  push:
    branches:
      - master
      - main
    paths:
      - 'docs/**'
  workflow_dispatch:

jobs:
  auth:
    runs-on: ubuntu-latest
    outputs:
      token: ${{ steps.app-token.outputs.token }}
    steps:
      - run: |
          echo "APPLICATION ID: ${{ vars.DOCS_BUILDER_APP_ID }}"
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.DOCS_BUILDER_APP_ID }}
          private-key: ${{ secrets.DOCS_BUILDER_PRIVATE_KEY }}

  deploy:
    runs-on: ubuntu-latest
    needs: auth
    strategy:
      matrix:
        page:
          - {repo: Australian-Imaging-Service/Australian-Imaging-Service.github.io, branch: main}
          - {repo: Australian-Imaging-Service/web-dev, branch: master}
    steps:
      - name: Repository Dispatch
        run: |
          gh workflow run 'Deploy Hugo site to Pages' --ref ${{ matrix.page.branch }}
        env:
          GH_REPO: ${{ matrix.page.repo }}
          GH_TOKEN: ${{ needs.auth.outputs.token }}
